# Generated by Django 2.0.6 on 2019-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('make', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
